CREATE DATABASE AWS_COURSES;

CREATE TABLE TRAINERS (
  TRAINER_ID INTEGER PRIMARY KEY,
  TRAINER_NAME VARCHAR(200)
);

INSERT INTO TRAINERS VALUES (1, 'Ivan');
INSERT INTO TRAINERS VALUES (2, 'Petro');

SELECT * FROM TRAINERS;
